server:
  port: 8801 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          routes:
            - id: user-service
              uri: lb://consumer #使用nacos本地负载均衡策略
              #断言规则
              predicates:
                - Path=/**
    nacos:
      config:
        enabled: true # 如果不想使用 Nacos 进行配置管理，设置为 false 即可
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP # 项目组，默认为 DEFAULT_GROUP
        namespace: dev #指定命名空间： 开发、测试、补丁、生产环境 默认为public
        file-extension: yaml # 配置内容的数据格式，默认为 properties
      discovery:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP