#自定义参数
providerName: ${providerName}

spring:
  datasource:
   # url: jdbc:mysql://127.0.0.1:3306/jeecg-boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    url: ${provider.datasource.url}
    username: ${provider.datasource.username}
    password: ${provider.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
      # 配置获取连接等待超时的时间
    maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
  #我们还可以使用springboot的template的一些默认配置
  jdbc:
    template:
      query-timeout: 3   #超过3秒没有查询到数据就算是查询超时
  cloud:
    bootstrap:
      enabled: true
    nacos:
      config:
        enabled: true # 如果不想使用 Nacos 进行配置管理，设置为 false 即可
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP # 项目组，默认为 DEFAULT_GROUP
        #namespace: public #指定命名空间： 开发、测试、补丁、生产环境 默认为public
        file-extension: yaml # 配置内容的数据格式，默认为 properties
        prefix: provider
        #扩展配置:feign
      discovery:
        server-addr: 127.0.0.1:8848
        service: provider
        group: DEFAULT_GROUP # 项目组，默认为 DEFAULT_GROUP
        #namespace: public #指定命名空间： 开发、测试、补丁、生产环境 默认为public

#mybatis
mybatis-plus:
  type-aliases-package: org.yxs.provider.**.**.entity   # 所有Entity别名类所在包
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置打印日志
    call-setters-on-nulls: true
    cache-enabled: false


